<?php
/**
 * @file
 * Install function for the download module.
 */

/**
 * Implements hook_field_schema().
 */
function download_field_schema($field) {
  $columns = array(
    'download_fields' => array(
      'type' => 'varchar',
      'length' => 255,
      'not null' => FALSE,
    ),
    'download_label' => array(
      'type' => 'varchar',
      'length' => 255,
      'not null' => FALSE,
    ),
  );
  return array(
    'columns' => $columns,
  );
}

/**
 * Implements hook_requirements().
 */
function download_requirements($phase) {
  $requirements = array();
  if ($phase == 'runtime' && !class_exists('ZipArchive')) {
    $requirements['download_needs_zip'] = array(
      'title' => t('Download needs PHP Zip'),
      'value' => t('PHP Zip extension not available but required by the Download module.'),
      'description' => t('Class ZipArchive not found. Make sure the extension is enabled in your PHP installation. Without it the Download module is not able to build zip files.'),
      'severity' => REQUIREMENT_ERROR,
    );
  }
  return $requirements;
}
